theme: jekyll-theme-minimal
title: Irreverent Analysis By J.B Mountford 
description: Statistical modeling and analysis without any sense of seriousness or responcibility by unaffiliated researcher J.B Mountford
