# theme: jekyll-theme-cayman
remote_theme: chrisrhymes/bulma-clean-theme
# name: J.B. Mountford - Brighton Based Data Science & Statistical Analysis 
# title: J.B. Mountford -  Brighton Based Data Science & Statistical Analysis 
# description: Innovative, commercially impactful business modeling & analysis  by academically unaffiliated freelance researcher J.B Mountford
